<!DOCTYPE html>
<html lang="zh">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>card</title>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.1.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <style>
      .form-group {
        max-width: 600px;
      }

      button {
        margin-top: 20px;
      }

      .container {
        max-width: 600px;
        margin: 0px auto;
      }

      .card-video {
        max-width: 100%;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <form class="form-group" action="card/add" method="GET">
        <div>
          <label for="url-link">Link</label>
          <input type="text" class="form-control" id="url-link" name="page_url" placeholder="page link">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <div class="">
<?php
foreach ($cards as $uuid => $card) {
    echo <<<EOT
        <div id="$uuid" class="card">
          <a href="{$card['page_url']}">[link]</a> | <span>{$card['time']}</span>
          <video controls loop class="card-video" poster="{$card['image_url']}" src="{$card['video_url']}"></video>
        </div>
EOT;
}
?>
      </div>
    </div>
  </body>
</html>
